[build]
command = "npm run build"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

# Redirecionamentos específicos (devem vir antes do SPA routing)
[[redirects]]
from = "/profile"
to = "/perfil"
status = 301
force = true

[[redirects]]
from = "/calculadora"
to = "/"
status = 301
force = true

[[redirects]]
from = "/calculator"
to = "/"
status = 301
force = true

[[redirects]]
from = "/calc"
to = "/"
status = 301
force = true

# SPA routing - deve ser o último
[[redirects]]
from = "/*"
to = "/index.html"
status = 200