name = "worldshards-auth"
compatibility_date = "2024-01-01"

[env.production]
name = "worldshards-auth"

[env.preview]
name = "worldshards-auth-preview"

[[env.production.d1_databases]]
binding = "DB"
database_name = "worldshards-db"
database_id = "your-database-id"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "worldshards-db-preview"
database_id = "your-preview-database-id"